# Change these first
owner: TinkerHost # Your GitHub organization or username, where this repository lives
repo: upptime-free-hosting-central-servers # The name of this repository

sites:
  - name: QFW1
    url: $QFW1
    port: $PORT
    check: "tcp-ping"
  - name: QFW2
    url: $QFW2
    port: $PORT
    check: "tcp-ping"
  - name: QFW3
    url: $QFW3
    port: $PORT
    check: "tcp-ping"
  - name: QFW4
    url: $QFW4
    port: $PORT
    check: "tcp-ping"
  - name: QF5
    url: $QF5
    port: $PORT
    check: "tcp-ping"
  - name: QFW6
    url: $QFW6
    port: $PORT
    check: "tcp-ping"
  - name: PM1
    url: $PM1
    port: $PORT
    check: "tcp-ping"
  - name: PM2
    url: $PM2
    port: $PORT
    check: "tcp-ping"
  - name: PM4
    url: $PM4
    port: $PORT
    check: "tcp-ping"
  - name: FP5
    url: $FP5
    port: $PORT
    check: "tcp-ping"
  - name: FP6
    url: $FP6
    port: $PORT
    check: "tcp-ping"
  - name: FP7
    url: $FP7
    port: $PORT
    check: "tcp-ping"
  - name: FP8
    url: $FP8
    port: $PORT
    check: "tcp-ping"
  - name: FW33
    url: $FW33
    port: $PORT
    check: "tcp-ping"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: freehostingnodeuptime.tinkerhost.net
  # baseUrl: /your-repo-name
  logoUrl: https://tinkerhost.net/images/tinkerhost-512-09.svg
  name: TinkerHost Free Hosting Node Uptime Tracker
  introTitle: "TinkerHost Free Server Node Uptime"
  introMessage: Uptime center for TinkerHost free hosting nodes, powered by Upptime
  navbar:
    - title: Home
      href: https://tinkerhost.net/?ref=free-hosting-node-uptime
    - title: Status
      href: /
    - title: Community Forum
      href: https://community.tinkerhost.net/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
